### ISSUE TITLE
Unable to push the file to folder /data/

### ISSUE THREAD

**Issue by yakubpashask** [vmalyi/adb_android#37]
Hello, 
I am unable to push any files to the device/emulator and it always return the ('1','')
When i debug it says permission denied to copy.

Please help me.

Thanks
Yakub.

**Comment by vmalyi** [comment]
Did you just try to execute this command manually, without using adb_android lib?

Try "adb push '/source_folder/source_file.txt' '/destination_folder/' and observe the result.

If the error persists, refer to https://stackoverflow.com/questions/7399028/android-adb-permission-denied or similar topics in order to narrow down the problem. I doubt that this is an issue in adb_android lib.

**Comment by yakubpashask** [comment]
yes I did it.. without "su" it says permission denied in shell. but if I do "su" and then execute the command it works. but I am not sure how would execute su in shell with lib.

adb_android._exec_command('./adb shell su')
the above gives me the same permission denied error.

Thanks
Yakub.
